# 函数

---

​		函数的出现也提升了整个程序界代码复用的水平

## 函数声明

```go
func func_name(parameter_list) (return_list) {
    // body
}
```

- 在同一个 Go 包中，函数名应该是唯一的，并且它也遵守 Go 标识符的导出规则

- Go 函数支持变长参数,在类型前面增加“…”

- 返回值列表声明了这些返回值的类型

- 函数声明中的函数体是可选的

  > ​		没有函数体，说明这个函数可能是在 Go 语言之外实现的，比如使用汇编语言实现，然后通过链接器将实现与声明中的函数名链接到一起

### 参数列表

参数列表中的参数叫做形式参数（Parameter，简称形参），实际调用时传入的参数被称为实际参数（Argument，简称实参）。

Go 语言中，函数参数传递采用是值传递的方式。所谓“值传递”，就是将实际参数在内存中的表示逐位拷贝（Bitwise Copy）到形式参数中。

> 整型、数组、结构体，没有使用header结构的类型，值传递拷贝的就是它们自身。

string、切片、map，使用header结构的类型，值传递拷贝的是header结构，header指向同一个数据存储实例。

> - 这些类型传递的开销是固定的，与数据内容大小无关
> - 不拷贝实际数据内容的拷贝过程，也被称为“浅拷贝”

接口形参、变长形参时：

- 接口类型，Go 编译器会把传递的实参赋值给对应的接口类型形参

- 变长形参，Go 编译器会将零个或多个实参按一定形式转换为对应的变长形参。

  ```go
  
  func myAppend(sl []int, elems ...int) []int {
      fmt.Printf("%T\n", elems) // []int
      if len(elems) == 0 {
          println("no elems to append")
          return sl
      }
  
      sl = append(sl, elems...)
      return sl
  }
  
  func main() {
      sl := []int{1, 2, 3}
      sl = myAppend(sl) // no elems to append
      fmt.Println(sl) // [1 2 3]
      sl = myAppend(sl, 4, 5, 6)
      fmt.Println(sl) // [1 2 3 4 5 6]
  }
  
  // 在 Go 中，变长参数实际上是通过切片来实现的
  ```

### 返回值列表

和其他主流静态类型语言，比如 C、C++ 和 Java 不同，Go 函数支持多返回值。将更多结果信息返回给它的调用者，Go 语言的错误处理机制更加现代。

不需要具名所有返回值，通过返回值列表参数来返回值

- 一个返回值，不需要将返回值用括号括起来

- 为每个返回值声明变量名，被称为具名返回值（Named Return Value）

  - Go 标准库以及大多数项目代码中的函数，都选择了使用普通的非具名返回值形式
  - 当函数使用 defer，而且还在 defer 函数中修改外部函数返回值时，具名返回值可以让代码显得更优雅清晰
  - 返回值个数较多时,具名返回值可以让函数实现的可读性更好一些

  ```go
  
  // $GOROOT/src/time/format.go
  func parseNanoseconds(value string, nbytes int) (ns int, rangeErrString string, err error) {
      if !commaOrPeriod(value[0]) {
          err = errBad
          return
      }
      if ns, err = atoi(value[1:nbytes]); err != nil {
          return
      }
      if ns < 0 || 1e9 <= ns {
          rangeErrString = "fractional second"
          return
      }
  
      scaleDigits := 10 - nbytes
      for i := 0; i < scaleDigits; i++ {
          ns *= 10
      }
      return
  }
  ```

## 函数签名

函数声明中的 func 关键字、参数列表和返回值列表共同构成了函数类型。而参数列表与返回值列表的组合也被称为函数签名，它是决定两个函数类型是否相同的决定因素。

在函数签名中， 省略函数签名参数列表中的参数名，以及返回值列表中的返回值变量名。

```go
func(io.Writer, string, ...interface{}) (int, error)
```

基于函数类型自定义类型（函数指针类型）

```go
// $GOROOT/src/net/http/server.go
type HandlerFunc func(ResponseWriter, *Request)

// $GOROOT/src/sort/genzfunc.go
type visitFunc func(ast.Node) ast.Visitor
```



## 函数对象

签名相同的函数类型，是相同类型。每个函数声明所定义的函数，仅仅是对应的函数类型的一个实例。

```go
var func_name = func(parameter_list) (return_list) {
    // body
}
```

```go
func_name := func(parameter_list) (return_list) {
    // body
}
```

### 一等公民

即，函数可以视为对象。

> 如果一门编程语言对某种语言元素的创建和使用没有限制，我们可以像对待值 (value) 一样对待这种语法元素，那么我们就称这种语法元素是这门编程语言的“一等公民”。拥有“一等公民”待遇的语法元素可以存储在变量中，可以作为参数传递给函数，可以在函数内部创建并可以作为返回值从函数返回。基于这个解释，我们来看看 Go 语言的函数作为“一等公民”，表现出的各种行为特征。
>
> ​										——沃德·坎宁安 (Ward Cunningham)
>
> ​	[wiki.c2.com//?FirstClass](http://wiki.c2.com//?FirstClass)

- 存储在变量中 —— 对象

  可以声明一个函数类型的对象

  ```go
  
  var (
      myFprintf = func(w io.Writer, format string, a ...interface{}) (int, error) {
          return fmt.Fprintf(w, format, a...)
      }
  )
  
  func main() {
      fmt.Printf("%T\n", myFprintf) // func(io.Writer, string, ...interface {}) (int, error)
      myFprintf(os.Stdout, "%s\n", "Hello, Go") // 输出Hello，Go
  }
  ```

- 在函数内创建并通过返回值返回

  实际上仍然是返回一个局部的函数对象：`var func_name = func()...`

  ```go
  
  func setup(task string) func() {
      println("do some setup stuff for", task)
      return func() {
          println("do some teardown stuff for", task)
      }
  }
  
  func main() {
      teardown := setup("demo")
      defer teardown()
      println("do some bussiness stuff")
  }
  ```

  > ​		模拟了执行一些重要逻辑之前的上下文建立（setup），以及之后的上下文拆除（teardown）。在一些单元测试的代码中，我们也经常会在执行某些用例之前，建立此次执行的上下文（setup），并在这些用例执行后拆除上下文（teardown），避免这次执行对后续用例执行的干扰。

  > ​		匿名函数定义时自动捕获上下文环境中的实体，这样的匿名函数在 Go 中也被称为闭包（Closure）。
  >
  > > ​		闭包本质上就是一个匿名函数或叫函数字面值，它们可以引用它的包裹函数，也就是创建它们的函数中定义的变量。然后，这些变量在包裹函数和匿名函数之间共享，只要闭包可以被访问，这些共享的变量就会继续存在。

- 作为参数传入函数

  ```go
  time.AfterFunc(time.Second*2, func() { println("timer fired") })
  ```

- 拥有类型

  函数签名即函数对象的类型。

### 使用

#### 函数类型

​		函数也可以被显式转型：

```go

func greeting(w http.ResponseWriter, r *http.Request) {
    fmt.Fprintf(w, "Welcome, Gopher!\n")
}                    

func main() {
    http.ListenAndServe(":8080", http.HandlerFunc(greeting))
}
```

```go

// $GOROOT/src/net/http/server.go
func ListenAndServe(addr string, handler Handler) error {
    server := &Server{Addr: addr, Handler: handler}
    return server.ListenAndServe()
}
```

```go

// $GOROOT/src/net/http/server.go
type Handler interface {
    ServeHTTP(ResponseWriter, *Request)
}


// $GOROOT/src/net/http/server.go

type HandlerFunc func(ResponseWriter, *Request)

// ServeHTTP calls f(w, r).
func (f HandlerFunc) ServeHTTP(w ResponseWriter, r *Request) {
        f(w, r)
}
```

> http.HandlerFunc(greeting)这句代码的真正含义，是将函数 greeting 显式转换为 HandlerFunc 类型
>
> HandlerFunc 是一个基于函数类型定义的新类型，它的底层类型为函数类型func(ResponseWriter, *Request)。这个类型有一个方法 ServeHTTP，然后实现了 Handler 接口。
>
> HandlerFunc 的底层类型是func(ResponseWriter, *Request)，与 greeting 函数的类型是一致的，这和下面整型变量的显式转型原理也是一样的：
>
> ```go
> type MyInt int
> var x int = 5
> y := MyInt(x) // MyInt的底层类型为int，类比HandlerFunc的底层类型为func(ResponseWriter, *Request)
> ```

#### 闭包简化函数调用

减少参数的重复输入

```go

func times(x, y int) int {
  return x * y
}
```

```go

func partialTimes(x int) func(int) int {
  return func(y int) int {
    return times(x, y)
  }
}
```

```go

func main() {
  timesTwo := partialTimes(2)   // 以高频乘数2为固定乘数的乘法函数
  timesThree := partialTimes(3) // 以高频乘数3为固定乘数的乘法函数
  timesFour := partialTimes(4)  // 以高频乘数4为固定乘数的乘法函数
  fmt.Println(timesTwo(5))   // 10，等价于times(2, 5)
  fmt.Println(timesTwo(6))   // 12，等价于times(2, 6)
  fmt.Println(timesThree(5)) // 15，等价于times(3, 5)
  fmt.Println(timesThree(6)) // 18，等价于times(3, 6)
  fmt.Println(timesFour(5))  // 20，等价于times(4, 5)
  fmt.Println(timesFour(6))  // 24，等价于times(4, 6)
}
```



## defer

defer 是 Go 语言提供的一种延迟调用机制.

- 在 Go 中，只有在函数（和方法）内部才能使用 defer；
- defer 关键字后面只能接函数（或方法），这些函数被称为 deferred 函数。

### defer机制

defer 将它们注册到其所在 Goroutine 中，用于存放 deferred 函数的栈数据结构中，这些 deferred 函数将在执行 defer 的函数退出前，按后进先出（LIFO）的顺序被程序调度执行：

![img](https://static001.geekbang.org/resource/image/89/c0/89d2f5ec28f6c291bf44deb4c5f979c0.jpg?wh=1920x1080)

defer内部的recover只能捕获当前协程的Panic，不能跨协程执行

### 延迟清理

deferred 函数可以在任何情况下为函数进行收尾工作。

> 无论是执行到函数体尾部返回，还是在某个错误处理分支显式 return，又或是出现 panic，已经存储到 deferred 函数栈中的函数，都会被调度执行。

```go

func doSomething() error {
    var mu sync.Mutex
    mu.Lock()

    r1, err := OpenResource1()
    if err != nil {
        mu.Unlock()
        return err
    }

    r2, err := OpenResource2()
    if err != nil {
        r1.Close()
        mu.Unlock()
        return err
    }

    r3, err := OpenResource3()
    if err != nil {
        r2.Close()
        r1.Close()
        mu.Unlock()
        return err
    }

    // 使用r1，r2, r3
    err = doWithResources() 
    if err != nil {
        r3.Close()
        r2.Close()
        r1.Close()
        mu.Unlock()
        return err
    }

    r3.Close()
    r2.Close()
    r1.Close()
    mu.Unlock()
    return nil
}

/////////////////////////////////////////////////////////

func doSomething() error {
    var mu sync.Mutex
    mu.Lock()
    defer mu.Unlock()

    r1, err := OpenResource1()
    if err != nil {
        return err
    }
    defer r1.Close()

    r2, err := OpenResource2()
    if err != nil {
        return err
    }
    defer r2.Close()

    r3, err := OpenResource3()
    if err != nil {
        return err
    }
    defer r3.Close()

    // 使用r1，r2, r3
    return doWithResources() 
}
```

### 跟踪调用栈

### 注意事项

#### defer的要求

对于有返回值的自定义函数或方法，返回值会在 deferred 函数被调度执行的时候被自动丢弃。

`append、cap、len、make、new、imag` 等内置函数都是不能直接作为 deferred 函数的，而 `close、copy、delete、print、recover` 等内置函数则可以直接被 defer 设置为 deferred 函数。

对于不能直接作为 deferred 函数的内置函数，使用匿名函数包裹来间接满足要求:

```go
defer func() {
  _ = append(sl, 11)
}()
```

#### defer的求值时机

defer 关键字后面的表达式，是在将 deferred 函数注册到 deferred 函数栈的时候进行求值的。

```go

func foo1() {
    for i := 0; i <= 3; i++ {
        defer fmt.Println(i)
    }
}

func foo2() {
    for i := 0; i <= 3; i++ {
        defer func(n int) {
            fmt.Println(n)
        }(i)
    }
}

func foo3() {
    for i := 0; i <= 3; i++ {
        defer func() {
            fmt.Println(i)
        }()
    }
}

func main() {
    fmt.Println("foo1 result:")
    foo1()
    fmt.Println("\nfoo2 result:")
    foo2()
    fmt.Println("\nfoo3 result:")
    foo3()
}
```

#### defer的性能损耗

defer 让我们进行资源释放（如文件描述符、锁）的过程变得优雅很多，也不易出错。但在性能敏感的应用中，defer 带来的性能负担也是我们必须要知晓和权衡的问题。

从 Go 1.13 版本开始，Go 核心团队对 defer 性能进行了多次优化，到现在的 Go 1.17 版本，defer 的开销已经足够小了。

带有 defer 的函数执行开销，仅是不带有 defer 的函数的执行开销的 1.45 倍左右.

## 错误处理

错误处理方式，是一门编程语言在设计早期就要确定下来的基本机制，它在很大程度上影响着编程语言的语法形式、语言实现的难易程度，以及语言后续的演进方向。

在 C 语言中，我们通常用一个类型为整型的函数返回值作为错误状态标识，函数调用者会基于值比较的方式，对这一代表错误状态的返回值进行检视。

> - 必须显式地去关注和处理每个错误，经过显式错误处理的代码会更健壮，也会让开发人员对这些代码更有信心。
> - 错误就是普通的值，所以我们不需要用额外的语言机制去处理它们
> - C 语言中的函数最多仅支持一个返回值，很多开发者会把这单一的返回值“一值多用”
>   - 一个返回值，不仅要承载函数要返回给调用者的信息，又要承载函数调用的最终错误状态
>   - 当返回值为其他类型，比如字符串的时候，我们还很难将它与错误状态融合到一起
>     - 要么使用输出参数，承载要返回给调用者的信息
>     - 要么自定义一个包含返回信息与错误状态的结构体，作为返回值类型
>
> ```c
> // stdio.h
> int fprintf(FILE * restrict stream, const char * restrict format, ...);
> ```

​		Go 函数增加了多返回值机制，来支持错误状态与返回信息的分离，并建议开发者把要返回给调用者的信息和错误状态标识，分别放在不同的返回值中。

```go
// fmt包
func Fprintf(w io.Writer, format string, a ...interface{}) (n int, err error)
    
// 返回值 n 用来表示写入 io.Writer 中的字节个数
// 返回值 err 表示这个函数调用的最终状态，如果成功，err 值就为 nil，不成功就为特定的错误值。
```

​		代表错误状态的变量 err 的类型，并不是一个传统使用的整数类型，而是用了一个名为 error 的类型。

### error

​		依然可以像传统的 C 语言那样，用一个整型值来表示错误状态，但 Go 语言惯用法，是使用 error 这个接口类型表示错误，并且按惯例，我们通常将 error 类型返回值放在返回值列表的末尾。

```go
// $GOROOT/src/builtin/builtin.go
type interface error {
    Error() string
}
```

- 任何实现了 error 的 Error 方法的类型的实例，都可以作为错误值赋值给 error 接口变量。

- 标准库中提供了两种方便 Go 开发者构造错误值的方法： `errors.New`和``fmt.Errorf``

  ```go
  err := errors.New("your first demo error")
  errWithCtx = fmt.Errorf("index %d is out of bounds", i)
  ```

  返回的是同一个实现了 error 接口的类型的实例，这个未导出的类型就是`errors.errorString`

  提供的错误上下文（Error Context）只限于以字符串形式呈现的信息，也就是 Error 方法返回的信息。

  ```go
  
  // $GOROOT/src/errors/errors.go
  
  type errorString struct {
      s string
  }
  
  func (e *errorString) Error() string {
      return e.s
  }
  ```

- 自定义错误类型，从错误值中提取出更多信息，帮助选择错误处理路径

  ```go
  //$GOROOT/src/net/net.go
  type OpError struct {
      Op string
      Net string
      Source Addr
      Addr Addr
      Err	error
  }
  
  //////////////////////
  
  // $GOROOT/src/net/http/server.go
  func isCommonNetReadError(err error) bool {
      if err == io.EOF {
          return true
      }
      if neterr, ok := err.(net.Error); ok && neterr.Timeout() {
          return true
      }
      if oe, ok := err.(*net.OpError); ok && oe.Op == "read" {
          return true
      }
      return false
  }
  ```



​		error统一了错误类型，构造的错误都是值，易扩展，支持自定义错误上下文。error 接口是错误值的提供者与错误值的检视者之间的契约。error 接口的实现者负责提供错误上下文，供负责错误处理的代码使用。

> ​		错误具体上下文与作为错误值类型的 error 接口类型的解耦，也体现了 Go 组合设计哲学中“正交”的理念。

### 错误处理策略

#### 透明错误处理策略

​		完全不关心返回错误值携带的具体上下文信息，只要发生错误就进入唯一的错误处理执行路径。

​		是Go 语言中最常见的错误处理策略，80% 以上的 Go 错误处理情形都可以归类到这种策略下

```go

err := doSomething()
if err != nil {
    // 不关心err变量底层错误值所携带的具体上下文信息
    // 执行简单错误处理逻辑并返回
    ... ...
    return err
}
```

​		由于错误处理方并不关心错误值的上下文，所以错误值的构造可以直接使用 `errors.New`和``fmt.Errorf``

```go
func doSomething(...) error {
    ... ...
    return errors.New("some error occurred")
}
```

> ​		错误值代表的上下文信息，对错误处理方是透明的，因此这种策略称为“透明错误处理策略”。在错误处理方不关心错误值上下文的前提下，透明错误处理策略能最大程度地减少错误处理方与错误值构造方之间的耦合关系

##### 反模式

​		错误处理方会尝试对返回的错误值进行检视。错误处理方以透明错误值所能提供的唯一上下文信息（描述错误的字符串），作为错误处理路径选择的依据。但这种“反模式”会造成严重的隐式耦合。

```go

data, err := b.Peek(1)
if err != nil {
    switch err.Error() {
    case "bufio: negative count":
        // ... ...
        return
    case "bufio: buffer full":
        // ... ...
        return
    case "bufio: invalid use of UnreadByte":
        // ... ...
        return
    default:
        // ... ...
        return
    }
}
```

> ​		错误值构造方不经意间的一次错误描述字符串的改动，都会造成错误处理方处理行为的变化，并且这种通过字符串比较的方式，对错误值进行检视的性能也很差。

#### 哨兵错误处理策略

​		定义导出的（Exported）“哨兵”错误值的方式，来辅助错误处理方检视（inspect）错误值并做出错误处理分支的决策。

```go

// $GOROOT/src/bufio/bufio.go
var (
    ErrInvalidUnreadByte = errors.New("bufio: invalid use of UnreadByte")
    ErrInvalidUnreadRune = errors.New("bufio: invalid use of UnreadRune")
    ErrBufferFull        = errors.New("bufio: buffer full")
    ErrNegativeCount     = errors.New("bufio: negative count")
)

////////////////////////////


data, err := b.Peek(1)
if err != nil {
    switch err {
    case bufio.ErrNegativeCount:
        // ... ...
        return
    case bufio.ErrBufferFull:
        // ... ...
        return
    case bufio.ErrInvalidUnreadByte:
        // ... ...
        return
    default:
        // ... ...
        return
    }
}
```

> ​		一般“哨兵”错误值变量以 ErrXXX 格式命名。和透明错误策略相比，“哨兵”策略让错误处理方在有检视错误值的需求时候，可以“有的放矢”。

##### errors.Is

暴露“哨兵”错误值也意味着这些错误值和包的公共函数 / 方法一起成为了 API 的一部分。一旦发布出去，开发者就要对它进行很好的维护。“哨兵”错误值也让使用这些值的错误处理方对它产生了依赖。

标准库 errors 包提供了 Is 函数用于错误处理方对错误值的检视。

```go

// 类似 if err == ErrOutOfBounds{ … }
if errors.Is(err, ErrOutOfBounds) {
    // 越界的错误处理
}
```

如果 error 类型变量的底层错误值是一个包装错误，errors.Is 方法会沿着该包装错误所在错误链（Error Chain)，与链上所有被包装的错误（Wrapped Error）进行比较，直至找到一个匹配的错误为止。

```go

var ErrSentinel = errors.New("the underlying sentinel error")

func main() {
  err1 := fmt.Errorf("wrap sentinel: %w", ErrSentinel)
  err2 := fmt.Errorf("wrap err1: %w", err1)
    println(err2 == ErrSentinel) //false
  if errors.Is(err2, ErrSentinel) {
    println("err2 is ErrSentinel")
    return
  }

  println("err2 is not ErrSentinel")
}

// 通过 fmt.Errorf 函数，并且使用 %w 创建包装错误变量 err1 和 err2，其中 err1 实现了对 ErrSentinel 这个“哨兵错误值”的包装，而 err2 又对 err1 进行了包装，这样就形成了一条错误链
```

> ​		 Go 1.13 及后续版本，尽量使用errors.Is方法去检视错误值，或者包装了“哨兵”的错误值。

#### 错误值类型检视策略

由于错误值都通过 error 接口变量统一呈现，要得到底层错误类型携带的错误上下文信息，错误处理方需要使用 Go 提供的类型断言机制（Type Assertion）或类型选择机制（Type Switch）.

```go

// $GOROOT/src/encoding/json/decode.go
type UnmarshalTypeError struct {
    Value  string       
    Type   reflect.Type 
    Offset int64        
    Struct string       
    Field  string      
}

// 错误处理方可以通过错误类型检视策略，获得更多错误值的错误上下文信息

// $GOROOT/src/encoding/json/decode.go
func (d *decodeState) addErrorContext(err error) error {
    if d.errorContext.Struct != nil || len(d.errorContext.FieldStack) > 0 {
        switch err := err.(type) {
        case *UnmarshalTypeError:
            err.Struct = d.errorContext.Struct.Name()
            err.Field = strings.Join(d.errorContext.FieldStack, ".")
            return err
        }
    }
    return err
}
```

一般自定义导出的错误类型以XXXError的形式命名。这些错误类型也和包的公共函数 / 方法一起，成为了 API 的一部分。类型进行检视的错误处理方对其具有依赖。

##### errors.As

 		Go 1.13 版本开始，标准库 errors 包提供了As函数给错误处理方检视错误值。As函数类似于通过类型断言判断一个 error 类型变量是否为特定的自定义错误类型

```go

// 类似 if e, ok := err.(*MyError); ok { … }
var e *MyError
if errors.As(err, &e) {
    // 如果err类型为*MyError，变量e将被设置为对应的错误值
}
```

如果 error 类型变量的动态错误值是一个包装错误，errors.As函数会沿着该包装错误所在错误链，与链上所有被包装的错误的类型进行比较，直至找到一个匹配的错误类型

```go

type MyError struct {
    e string
}

func (e *MyError) Error() string {
    return e.e
}

func main() {
    var err = &MyError{"MyError error demo"}
    err1 := fmt.Errorf("wrap err: %w", err)
    err2 := fmt.Errorf("wrap err1: %w", err1)
    var e *MyError
    if errors.As(err2, &e) {
        println("MyError is on the chain of err2")
        println(e == err)                  
        return                             
    }                                      
    println("MyError is not on the chain of err2")
} 
```

> ​		 Go 1.13 及后续版本，尽量使用errors.As方法去检视错误值.

#### 错误行为特征检视策略

将某个包中的错误类型归类，统一提取出一些公共的错误行为特征，并将这些错误行为特征放入一个公开的接口类型中。

```go
// 将包内的所有错误类型的公共行为特征抽象并放入net.Error这个接口中
// $GOROOT/src/net/net.go
type Error interface {
    error
    Timeout() bool  
    Temporary() bool
}

// net.Error 用于判断错误行为特征的方法：
// 	Timeout 用来判断是否是超时（Timeout）错误
// 	Temporary 用于判断是否是临时（Temporary）错误。
```

错误处理方只需要依赖这个公共接口，就可以检视具体错误值的错误行为特征信息，并根据这些信息做出后续错误处理分支选择的决策。

```go

// $GOROOT/src/net/http/server.go
func (srv *Server) Serve(l net.Listener) error {
    ... ...
    for {
        rw, e := l.Accept() // Accept 方法实际上返回的错误类型为OpError
        					// 自定义错误类型，它实现了错误公共特征接口net.Error
        if e != nil {
            select {
            case <-srv.getDoneChan():
                return ErrServerClosed
            default:
            }
            if ne, ok := e.(net.Error); ok && ne.Temporary() {
                // 注：这里对临时性(temporary)错误进行处理
                // OpError 实例可以被错误处理方通过net.Error接口的方法，判断它的行为是否满足 Temporary 或 Timeout 特征。
                ... ...
                time.Sleep(tempDelay)
                continue
            }
            return e
        }
        ...
    }
    ... ...
}



/////////////////////

// $GOROOT/src/net/net.go
type OpError struct {
    ... ...
    // Err is the error that occurred during the operation.
    Err error
}

type temporary interface {
    Temporary() bool
}

func (e *OpError) Temporary() bool {
  if ne, ok := e.Err.(*os.SyscallError); ok {
      t, ok := ne.Err.(temporary)
      return ok && t.Temporary()
  }
  t, ok := e.Err.(temporary)
  return ok && t.Temporary()
}
```



#### 总结

​		“透明错误处理策略”和行为特征检视，有效降低了错误的构造方与错误处理方两者之间的耦合。

​		哨兵和类型检视是实际编码中有效的错误处理策略，但在错误的构造方与错误处理方两者之间建立了耦合。



### 健壮性保证

- 不要相信任何外部输入的参数
- 不要忽略任何一个错误
- 不要假设异常不会发生



## 异常 panic

panic是go程序的运行时异常。

即便不是主goroutine中出现的异常，只要未被捕获，就会导致程序的执行终止。

### panicking

触发panic的情况有两种：

- Go运行时
- 主动调用panic函数触发

发生panicking时，函数将对已经求值的``defer``函数执行完后停止执行。将控制权返回调用者。panicking过程将随着函数返回被带出，在调用栈上传递，直到当前goroutine中所有的函数都返回为止，go程序随之崩溃退出。

```go

func foo() {
    println("call foo")
    bar()
    println("exit foo")
}

func bar() {
    println("call bar")
    panic("panic occurs in bar")
    zoo()
    println("exit bar")
}

func zoo() {
    println("call zoo")
    println("exit zoo")
}

func main() {
    println("call main")
    foo()
    println("exit main")
}


// 调用次序依次为main -> foo -> bar -> zoo
// bar call panic

/* result
call main
call foo
call bar
panic: panic occurs in bar
*/

// 日志"exit main"也没有得到输出的机会。
```



### 捕获 recover

通过``recover``来捕获并尝试恢复异常。

```go
func bar()
{
    defer func(){
        if e := recover(); e != nil {
            fmt.Println("recover the panic",)
        }
    }()
    
    println("call bar") 
    panic("panic occurs in bar") 
    zoo() 
    println("exit bar")
}

/*
call main
call foo
call bar
recover the panic: panic occurs in bar
exit foo
exit main
*/
```

recover 是 Go 内置的专门用于恢复 panic 的函数，它必须被放在一个 defer 函数中才能生效。

如果 recover 捕捉到 panic，它就会返回以 panic 的具体内容为错误上下文信息的错误值。如果没有 panic 发生，那么 recover 将返回 nil。而且，如果 panic 被 recover 捕捉到，panic 引发的 panicking 过程就会停止。

无论 bar 函数正常执行结束，还是因 panic 异常终止，在那之前设置成功的 defer 函数都会得到执行。匿名函数会调用 recover 把刚刚触发的 panic 恢复，这样，panic 还没等沿着函数栈向上走，就被消除了。

### 何时处理异常

#### 评估程序对 panic 的忍受度

针对各种应用对 panic 忍受度的差异，我们采取的应对 panic 的策略也应该有不同。像后端 HTTP 服务器程序这样的任务关键系统，我们就需要在特定位置捕捉并恢复 panic，以保证服务器整体的健壮度。

Go 标准库提供的 http server 采用的是，每个客户端连接都使用一个单独的 Goroutine 进行处理的并发处理模型。

> 无论在哪个 Goroutine 中发生未被恢复的 panic，整个程序都将崩溃退出。所以，为了保证处理某一个客户端连接的 Goroutine 出现 panic 时，不影响到 http server 主 Goroutine 的运行，Go 标准库在 serve 方法中加入了对 panic 的捕捉与恢复。
>
> ```go
> 
> // $GOROOT/src/net/http/server.go
> // Serve a new connection.
> func (c *conn) serve(ctx context.Context) {
>     c.remoteAddr = c.rwc.RemoteAddr().String()
>     ctx = context.WithValue(ctx, LocalAddrContextKey, c.rwc.LocalAddr())
>     defer func() {
>         if err := recover(); err != nil && err != ErrAbortHandler {
>             const size = 64 << 10
>             buf := make([]byte, size)
>             buf = buf[:runtime.Stack(buf, false)]
>             c.server.logf("http: panic serving %v: %v\n%s", c.remoteAddr, err, buf)
>         }
>         if !c.hijacked() {
>             c.close()
>             c.setState(c.rwc, StateClosed, runHooks)
>         }
>     }()
>     ... ...
> }
> ```
>
> 即便处理某个客户端连接的 Goroutine 出现 panic，处理其他连接 Goroutine 以及 http server 自身都不会受到影响。
>
> 局部不要影响整体的异常处理策略，在很多并发程序中都有应用。
>
> 捕捉和恢复 panic 的位置通常都在子 Goroutine 的起始处，这样设置可以捕捉到后面代码中可能出现的所有 panic.

#### 提示潜在bug

> C 语言中有个很好用的辅助函数，断言（assert 宏）。在使用 C 编写代码时，我们经常在一些代码执行路径上，使用断言来表达这段执行路径上某种条件一定为真的信心。断言为真，则程序处于正确运行状态，断言为否就是出现了意料之外的问题，而这个问题很可能就是一个潜在的 bug，这时我们可以借助断言信息快速定位到问题所在。

Go 语言标准库中并没有提供断言之类的辅助函数，但我们可以使用 panic，部分模拟断言对潜在 bug 的提示功能：

```go

// $GOROOT/src/encoding/json/decode.go
... ...
//当一些本不该发生的事情导致我们结束处理时，phasePanicMsg将被用作panic消息
//它可以指示JSON解码器中的bug，或者
//在解码器执行时还有其他代码正在修改数据切片。

const phasePanicMsg = "JSON decoder out of sync - data changing underfoot?"

func (d *decodeState) init(data []byte) *decodeState {
    d.data = data
    d.off = 0
    d.savedError = nil
    if d.errorContext != nil {
        d.errorContext.Struct = nil
        // Reuse the allocated space for the FieldStack slice.
        d.errorContext.FieldStack = d.errorContext.FieldStack[:0]
    }
    return d
}

func (d *decodeState) valueQuoted() interface{} {
    switch d.opcode {
    default:
        panic(phasePanicMsg)

    case scanBeginArray, scanBeginObject:
        d.skip()
        d.scanNext()

    case scanBeginLiteral:
        v := d.literalInterface()
        switch v.(type) {
        case nil, string:
            return v
        }
    }
    return unquotedValue{}
}




// $GOROOT/src/encoding/json/encode.go

func (w *reflectWithString) resolve() error {
    ... ...
    switch w.k.Kind() {
    case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
        w.ks = strconv.FormatInt(w.k.Int(), 10)
        return nil
    case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
        w.ks = strconv.FormatUint(w.k.Uint(), 10)
        return nil
    }
    panic("unexpected map key type")
}

```

在 Go 标准库中，大多数 panic 的使用都是充当类似断言的作用的。

#### 异常与错误

Go 中的 panic 呢，更接近于 Java 的RuntimeException+Error，而不是checked exception。我们前面提到过 Java 的checked exception是必须要被上层代码处理的，也就是要么捕获处理，要么重新抛给更上层。但是在 Go 中，我们通常会导入大量第三方包，而对于这些第三方包 API 中是否会引发panic，我们是不知道的。

API 调用者根本不会去逐一了解 API 是否会引发panic，也没有义务去处理引发的 panic。不要将 panic 当作错误返回给 API 调用者。

